In [1]:
from numpy import *
from sklearn import datasets

iris = datasets.load_iris()
samples = iris.data
target = iris.target

print samples[0], target[0]
print samples[-1], target[-1]

[ 5.1  3.5  1.4  0.2] 0
[ 5.9  3.   5.1  1.8] 2


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=11)

print iris.data.shape, iris.target.shape
print X_train.shape, y_train.shape, X_test.shape, y_test.shape

(150L, 4L) (150L,)
(90L, 4L) (90L,) (60L, 4L) (60L,)


In [22]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

SEED = 43
model = LogisticRegression()

mean_auc = 0.0
n = 10  # repeat the CV procedure 10 times to get more precise results
for i in range(n):
    # for each iteration, randomly hold out 20% of the data as CV set
    X_train, X_cv, y_train, y_cv = train_test_split(samples, target, test_size=.20, random_state=i*SEED)

    # if you want to perform feature selection / hyperparameter optimization, this is where you want to do it

    # train model and make predictions
    model.fit(X_train, y_train) 
    preds = model.predict_proba(X_cv)[:, 1]

    # compute AUC metric for this CV fold
    fpr, tpr, thresholds = metrics.roc_curve(y_cv, preds)
    roc_auc = metrics.auc(fpr, tpr)
    print "AUC (fold %d/%d): %f" % (i + 1, n, roc_auc)
    mean_auc += roc_auc

print "Mean AUC: %f" % (mean_auc/n)

ValueError: Data is not binary and pos_label is not specified

In [15]:
preds = lr.predict_proba(X_test)
preds[:, 1]

array([ 0.29885972,  0.23361655,  0.49065265,  0.53773288,  0.35568124,
        0.20455276,  0.84362658,  0.03546209,  0.19213648,  0.59650382,
        0.46997585,  0.87969799,  0.36503469,  0.29680769,  0.30098951,
        0.3090947 ,  0.3387322 ,  0.42386948,  0.27802468,  0.29442274,
        0.80875221,  0.1461773 ,  0.07340687,  0.70557246,  0.21179493,
        0.13660059,  0.2810578 ,  0.82874484,  0.059089  ,  0.47784428,
        0.12030754,  0.22529272,  0.42800695,  0.14841968,  0.16789297,
        0.42013719,  0.38274433,  0.52316455,  0.12997637,  0.39920192,
        0.77271761,  0.34484536,  0.10489578,  0.74825236,  0.25709219,
        0.69079133,  0.82756269,  0.15237753,  0.42794184,  0.09013276,
        0.22491971,  0.24882246,  0.61976598,  0.28110345,  0.74562954,
        0.13388771,  0.16931646,  0.69883209,  0.07806756,  0.11856897])

In [18]:
from sklearn import metrics

print 'log_loss: %f' % (metrics.log_loss(y_test, preds))

fpr, tpr, thresholds = metrics.roc_curve(y_test, preds[:,1])
roc_auc = metrics.auc(fpr, tpr)
print "AUC (fold %d/%d): %f" % (i + 1, n, roc_auc)

 log_loss: 0.335964


ValueError: Data is not binary and pos_label is not specified

In [6]:
from sklearn.metrics import accuracy_score
# http://datascience.stackexchange.com/questions/6676/scikit-learn-getting-sgdclassifier-to-predict-as-well-as-a-logistic-regression